### ISSUE TITLE
consider breaking up error lines

### ISSUE THREAD

**Issue by uberfuzzy** [fastly/jekyll-sanity-checker#8]
I had tweaked the fastly-docs version of the checker to split up error messages across multiple lines

https://github.com/fastly/fastly-docs/commit/3695e546ef52217c33de18e7e82b80f1fb482d78#diff-729a709f8287dd5409a3629363b93271

the single error line are quite extremely long because it prints the full filepath to the html + the full html object that had the error + a quite verbose error string

![error_with_line_breaks](https://cloud.githubusercontent.com/assets/1438723/5364283/6fe18482-7fb0-11e4-9c5f-37825633f38a.png)

the change was to make it easier for end users to not get glazed over eyes staring at a wall of error text for the 2 bits they actually needed (what file, and what error)

this could also be achieved by wrapping the parts in colors of some sort, but this was a simpler version without dealing with color escape codes on different platforms

**Comment by uberfuzzy** [comment]
wondering if we could get this bumped anytime soon?
I'd settle for even just a \n between error triplets

**Comment by edmund-huber** [comment]
Submit a PR, sounds like you already did the work.
